server:
  port: 18081

eurkaserver:
  port: 19527
  ip: 180.76.242.6
myserver:
  ip: localhost

spring:
  application:
    name: zy-server
  zipkin:
    base-url: http://180.76.242.6:18084
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1.0

eureka:
  instance:
    prefer-ip-address: true
    hostname: ${myserver.ip}
    instance-id: ${myserver.ip}:${spring.application.name}:${server.port}
    ip-address: ${myserver.ip}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eurkaserver.ip}:${eurkaserver.port}/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"
hystrix:
  dashboard:
    proxy-stream-allow-list: "*"




