server:
  port: 18080
eurkaserver:
  port: 19527
  ip: 180.76.242.6
myserver:
  ip: localhost
spring:
  application:
    name: test-client1
  zipkin:
    base-url: http://180.76.242.6:18084
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1.0

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eurkaserver.ip}:${eurkaserver.port}/eureka/
  instance:
    prefer-ip-address: true
    #百度 180.76.242.6
    #阿里 39.99.43.45
    #腾讯 110.42.175.90
    ip-address: ${myserver.ip}
    instance-id: ${myserver.ip}




